Run on 2022-01-29 15:11:49.870159
exception occured in name l152lav-0.500000 submode remark_2 algorithm ST-K-C-S
Traceback (most recent call last):
  File "/Users/felixneussel/Documents/Uni/Vertiefung/Bachelorarbeit/Implementierung/MIQP_QP_Solver/performance_check.py", line 256, in Test_Run_npz
    solution,obj,runtime,times_in_sub,num_of_subs, status,gap = solve(problem_data,1e-5,np.infty,TIME_LIMIT,SUBPROBLEM_MODE,ALGORITHM,BIG_M,True)
  File "/Users/felixneussel/Documents/Uni/Vertiefung/Bachelorarbeit/Implementierung/MIQP_QP_Solver/Functional/multitree.py", line 30, in solve
    return ST(problem_data,tol,time_limit,subproblem_mode,True,True,True,big_M,optimized_binary_expansion)
  File "/Users/felixneussel/Documents/Uni/Vertiefung/Bachelorarbeit/Implementierung/MIQP_QP_Solver/Functional/multitree.py", line 266, in ST
    for v in initial_solution:
TypeError: 'NoneType' object is not iterable

